### ISSUE TITLE
¿Cuáles son los protocolos serie más usados?, nombre 3 y descríbalos.

### ISSUE THREAD

**Issue by guelo2019** [ISPC-TST-ARQUITECTURA-Y-CONECTIVIDAD/tarea1-grupo-7#5]

**Comment by recursosssbb** [comment]
[¿Cuáles son los protocolos serie más usados.pdf](https://github.com/ISPC-TST-ARQUITECTURA-Y-CONECTIVIDAD/tarea1-grupo-7/files/11256219/Cuales.son.los.protocolos.serie.mas.usados.pdf)
